version: 2.1
orbs:
  node: circleci/node@1.1.6
  cloudrun: circleci/gcp-cloud-run@1.0.2
jobs:
  "Check and build":
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  "Deploy on cloud run":
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - cloudrun/init
      - cloudrun/build:
          tag: 'eu.gcr.io/${GOOGLE_PROJECT_ID}/frontend:${CIRCLE_SHA1}'
      - run:
          command: >
            SERVICE_NAME=frontend
            gcloud beta run deploy ${SERVICE_NAME} \
              --image "eu.gcr.io/${GOOGLE_PROJECT_ID}/${SERVICE_NAME}:${CIRCLE_SHA1}" \
              --platform managed \
              --region ${GOOGLE_COMPUTE_ZONE} \
              --port 80 \
              --set-env-vars "DECISION_SERVICE_URL=${DECISION_SERVICE_URL}"
            echo
            echo "Service deployed"
            echo
            gcloud beta run services add-iam-policy-binding --region=${GOOGLE_COMPUTE_ZONE} --member=allUsers --role=roles/run.invoker ${SERVICE_NAME}
            GET_GCP_DEPLOY_ENDPOINT=`gcloud beta run services describe ${SERVICE_NAME} --platform managed --region ${GOOGLE_COMPUTE_ZONE} --format="value(status.address.url)"`
            echo "export GCP_DEPLOY_ENDPOINT=$GET_GCP_DEPLOY_ENDPOINT" >> $BASH_ENV
            source $BASH_ENV
            echo $GCP_DEPLOY_ENDPOINT
          name: Cloud Run Deploy
workflows:
  "default":
    jobs:
      - "Check and build":
          filters:
            branches:
              ignore:
                - master
      - "Deploy on cloud run":
          filters:
            branches:
              only:
                - master
